const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('sbAPI', {
  openLevel: () => ipcRenderer.invoke('dialog:open-level'),
  openLevelFolder: () => ipcRenderer.invoke('dialog:open-level-folder'),
  pickFile: (opts) => ipcRenderer.invoke('dialog:pick-file', opts),
  projectCreate: (p) => ipcRenderer.invoke('project:create', p),
  projectOpen: (p) => ipcRenderer.invoke('project:open', p),
  projectExists: (p) => ipcRenderer.invoke('project:exists', p),
  projectUpdateFile: (p) => ipcRenderer.invoke('project:update-file', p),
  applyLevel: (p) => ipcRenderer.invoke('project:apply-level', p),
  projectSetEditable: (p) => ipcRenderer.invoke('project:set-editable', p),
  saveProjectState: (p) => ipcRenderer.invoke('project:save-state', p),
  projectImportLevel: (payload) => ipcRenderer.invoke('project:import-level', payload),
  projectImportLevelPath: (payload) => ipcRenderer.invoke('project:import-level-path', payload),
  projectImportLevelTo: (payload) => ipcRenderer.invoke('project:import-level-to', payload),
  getPathForFile: (file) => webUtils.getPathForFile(file),
  saveProjectAs: (defaultName) => ipcRenderer.invoke('dialog:save-project', defaultName),
  importJsonFile: () => ipcRenderer.invoke('dialog:import-json'),
  saveJsonDialog: (payload) => ipcRenderer.invoke('dialog:save-json', payload),
  openFolderDialog: () => ipcRenderer.invoke('dialog:open-folder'),
  readFileBuffer: (p) => ipcRenderer.invoke('level:read-file-buffer', p),
  readFileText: (p) => ipcRenderer.invoke('level:read-file-text', p),
  levelAddAsset: (payload) => ipcRenderer.invoke('level:add-asset', payload),
  saveStoryboard: (payload) => ipcRenderer.invoke('storyboard:save', payload),
  exportStoryboard: (payload) => ipcRenderer.invoke('project:export-storyboard', payload),
  packLevel: (payload) => ipcRenderer.invoke('project:pack-level', payload),
  saveLevelAs: (defaultName) => ipcRenderer.invoke('dialog:save-level-as', defaultName),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setSettings: (s) => ipcRenderer.invoke('settings:set', s),
  appVersion: () => ipcRenderer.invoke('app:version'),
  openPath: (p) => ipcRenderer.invoke('app:open-path', p),
  openExternal: (url) => ipcRenderer.invoke('app:open-external', url),
  repairFileAssociations: () => ipcRenderer.invoke('app:repair-file-associations'),
  pickFolder: (opts) => ipcRenderer.invoke('dialog:pick-folder', opts),
  getAsset: (name) => ipcRenderer.invoke('app:get-asset', name)
  ,
  rendererReady: () => ipcRenderer.send('app:renderer-ready'),
  onOpenProjectFile: (cb) => ipcRenderer.on('app:open-project-file', (e, p) => cb(p)),
  onConfirmClose: (cb) => ipcRenderer.on('app:confirm-close', () => cb()),
  confirmCloseDone: () => ipcRenderer.send('app:close-confirmed'),
  launchPlayer: (p) => ipcRenderer.invoke('player:launch-level', p),
  // 独立 Note 选择器工具窗口桥。
  nsOpen: () => ipcRenderer.invoke('tool:ns-open'),
  nsClose: () => ipcRenderer.invoke('tool:ns-close'),
  nsCall: (method, args) => ipcRenderer.invoke('tool:ns-call', method, args),
  nsPicked: (p) => ipcRenderer.send('app:renderer-ns-picked', p),
  nsOnPicked: (cb) => ipcRenderer.on('tool:ns-picked', (e, payload) => cb(payload)),
  nsSend: (msg) => ipcRenderer.send('app:renderer-ns-message', msg),
  nsOnMessage: (cb) => ipcRenderer.on('tool:ns-message', (e, m) => cb(m)),
  nsOnWindowState: (cb) => ipcRenderer.on('tool:ns-window-state', (e, s) => cb(s)),
  // 独立使用手册窗口桥。
  manualOpen: () => ipcRenderer.invoke('tool:manual-open'),
  readManual: () => ipcRenderer.invoke('docs:read-manual'),
  // 在线更新桥（electron-updater）。
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateDownload: () => ipcRenderer.invoke('update:download'),
  updateInstall: () => ipcRenderer.invoke('update:install'),
  onUpdateAvailable: (cb) => ipcRenderer.on('update:available', (e, p) => cb(p)),
  onUpdateProgress: (cb) => ipcRenderer.on('update:progress', (e, p) => cb(p)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update:downloaded', (e, p) => cb(p))
  ,
  // 语言切换联动：主窗口切换后通知独立窗口。
  notifyLanguageChanged: (lang) => ipcRenderer.send('app:language-changed', lang),
  onLanguageChanged: (cb) => ipcRenderer.on('app:language-changed', (e, lang) => cb(lang)),
  relaunchApp: () => ipcRenderer.invoke('app:relaunch')
});
