// Verify the win-unpacked asar contains the latest preview.js fixes.
const fs = require('fs');
const path = require('path');
const asarPath = path.join(__dirname, '..', 'app', 'dist', 'win-unpacked', 'resources', 'app.asar');
const asar = require(path.join(__dirname, '..', 'app', 'node_modules', '@electron', 'asar'));
const list = asar.listPackage(asarPath);
const get = (suffix) => {
  const hit = list.find((p) => p.replace(/\\/g, '/').endsWith(suffix));
  if (!hit) { console.error(suffix + ' not found in asar'); process.exit(1); }
  return asar.extractFile(asarPath, hit.replace(/^\\/, '')).toString('utf8');
};
const js = get('renderer/preview.js');
const sb = get('engine/storyboard.js');
const style2 = js.includes('ovr && ovr.style === 2');
const fxBelow = js.includes('Note clear effects render BELOW every note body');
const dragBody = js.includes('Drag/c-drag heads: the clear effect is bound to the head');
const mat3 = js.includes('stageMatrix3(obj, r, info)');
const ncPosOnly = js.includes('note-controller placeholder carries ONLY a position');
const rotzCcw = js.includes('Same sign convention as the note body: canvas rotates clockwise for a');
const chainGuard = js.includes('Guard against cyclic parent_id / target_id chains');
const cdragArrow = js.includes('The arrow angle is computed in SCREEN space; this frame carries');
const holdbarEdge = js.includes('The bar is attached to the hold body\'s CURRENT edge');
const spriteWarp = js.includes('drawSpriteWarped(ctx, img, obj, r, info, dw, dh');
const holdbar3d = js.includes("Render the bar's 3D rotation");
const camRotxKeep = js.includes('camera rot_x keeps the previously verified convention');
const childOpposite = js.includes('instead of flattening to the 2D result, so sprites parented to a');
const stageIndep = js.includes('they are independent of the game camera (no camera x/y/z/rotation)');
const opacityInherit = js.includes('Opacity cascades down the sprite parent chain');
const xoffRead = sb.includes('s.x_offset !== undefined');
const xoffWrite = sb.includes("key === 'dx'");
const hitboxKeep = sb.includes("'hitbox_multiplier'");
console.log('style2 fix in asar:', style2);
console.log('fx-below-notes fix in asar:', fxBelow);
console.log('drag-body effect fix in asar:', dragBody);
console.log('3D parent transform in asar:', mat3);
console.log('note-controller position-only in asar:', ncPosOnly);
console.log('stage rot_z counterclockwise in asar:', rotzCcw);
console.log('parent-chain cycle guard in asar:', chainGuard);
console.log('cdrag arrow camera compensation in asar:', cdragArrow);
console.log('holdbar starts at body edge in asar:', holdbarEdge);
console.log('sprite perspective trapezoid warp in asar:', spriteWarp);
console.log('holdbar 3D perspective in asar:', holdbar3d);
console.log('camera rot_x original convention in asar:', camRotxKeep);
console.log('parented child opposite depth in asar:', childOpposite);
console.log('stage layer camera-independent in asar:', stageIndep);
console.log('parent opacity cascade in asar:', opacityInherit);
console.log('XOffset/YOffset written for dx/dy in asar:', xoffWrite);
console.log('hitbox_multiplier preserved in asar:', hitboxKeep);
console.log('XOffset read in asar:', xoffRead);
process.exit(style2 && fxBelow && dragBody && mat3 && ncPosOnly && rotzCcw && chainGuard && cdragArrow && holdbarEdge && spriteWarp && holdbar3d && camRotxKeep && childOpposite && stageIndep && opacityInherit && xoffWrite && hitboxKeep && xoffRead ? 0 : 1);
